# Generated by Django 5.1.2 on 2024-10-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_jogo_url_jogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(default='avatar1', max_length=100),
        ),
    ]
